version: '3.7'

services:
  backend:
    image: ibrahimben/devops_project_backend:latest
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - database
    volumes:
      - backend_data:/app/data

  frontend:
    image: ibrahimben/devops_project_frontend:latest
    ports:
      - "80:80"
    environment:
      - API_URL=http://backend:8080
    depends_on:
      - backend

  database:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: devops
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  backend_data:
  db_data: