version: '3.7'

services:
  backend:
    image: ibrahimben/devops_project_backend:latest
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/devops
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
    depends_on:
      - database

  frontend:
    image: ibrahimben/devops_project_frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  database:
    image: mysql:latest
    environment:
    - MYSQL_DATABASE=devops
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: