global:
  scrape_interval:     15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['192.168.33.10:9090']
  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
    - targets: ['192.168.33.10:8081']
  - job_name: 'DevOps_Project'
    metrics_path: /backend
    static_configs:
    - targets: ['192.168.33.10:8080']